name: CICD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
    strategy:
      matrix:
        node-version: [15.3.0]
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Installation
        run: npm ci

      - name: build
        run: npm run build
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t charry .
      - name: Tags
        run: |
          docker tag charry ${{ secrets.DOCKER_USERNAME }}/charry:${{ github.sha }}
          docker tag charry ${{ secrets.DOCKER_USERNAME }}/charry:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/charry:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/charry:latest
