name: CICD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
    strategy:
      matrix:
        node-version: [15.3.0]
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Installation
        run: npm ci

      - name: build
        run: npm run build
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: docker-compose up --build -d

      - name: publish docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: charry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
